### ISSUE TITLE
ids not getting encoded

### ISSUE THREAD

**Issue by peterjslater** [mtvs/eloquent-hashids#10]
Hi

I am using laravel 7.7.1,  php 7.3.11

I have followed the instructions and installed composer eloquent-hashids module, however my ids are not getting encoded when I do a route call.

It seems I am missing something, do you have any ideas what I am missing ?

api.php is

`Route::get('pages', 'PageController@index');`

PageController is 

```
class PageController extends Controller
{
    public function index()
    {
        return Page::all();
    }

```

Page Model is

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Mtvs\EloquentHashids\HasHashid;
use Mtvs\EloquentHashids\HashidRouting;

class Page extends Model 
{
    use HasHashid, HashidRouting;

...

```

when I call
GET http://{{api-url}}/pages

I was expecting 

    "id": <hashKey>,
    "name": "My Page 1"

I still get the Id.

HTTP/1.1 200 OK
Date: Thu, 23 Apr 2020 00:53:50 GMT
Server: Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.3.11
Vary: Authorization
X-Powered-By: PHP/7.3.11
Cache-Control: no-cache, private
X-RateLimit-Limit: 500
X-RateLimit-Remaining: 499
Content-Length: 4241
Connection: close
Content-Type: application/json

[
  {
    "id": 1,
    "name": "My Page 1"

**Comment by mtvs** [comment]
Hi Peter,

This package adds the `hashid()` method to the model to generate the hashid. If you want it on the JSON version of your models in an HTTP response, you can use [Eloquent Resources](https://laravel.com/docs/7.x/eloquent-resources), for example:

```php
<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class Page extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'id' => $this->hashid(),
            'name' => $this->name,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
        ];
    }
}
```
```php
use App\Http\Resources\Page as PageResource;
use App\Page;

Route::get('/page', function () {
    return PageResource::collection(Page::all());
});
```
