### ISSUE TITLE
Feature request: validation rule

### ISSUE THREAD

**Issue by andrewminion-luminfire** [mtvs/eloquent-hashids#15]
I’m using eloquent hashids on a number of related objects, and often I am passing a `related_model_id` as part of my request.

Currently I’m only validating it as `string|required` but it would be great to be able to validate that the model actually exists, like the [`exists:table,column` validation rule](https://laravel.com/docs/master/validation#rule-exists).

Is that something you’d consider adding?

**Comment by mtvs** [comment]
I think it would probably be a better idea to just pass the actual id of the model. A hashid is more useful when is displayed to users.

**Comment by mtvs** [comment]
I would use hasids in views and original ids in api calls.

**Comment by limsocheat** [comment]
@andrewminion-luminfire 

you can try to 
```
$item = Outlet::findByHashidOrFail($hashid);
$id = $item->hashidToId($hashid);

$request->validate([
'name' => 'required|unique:outlets,name,' . $id,
]);
```
