### ISSUE TITLE
Unsupported operand types: int - string

### ISSUE THREAD

**Issue by SecondeJK** [mtvs/eloquent-hashids#17]
Steps:
1. Installed package via composer.
2. Import/use the hashId trait
3. In the tests, use a factory create method to make a model.
4. On the returned value, which is an model instance, called hashId() method.
5. Error.

`Unsupported operand types: int - string

  at vendor/hashids/hashids/src/Hashids.php:203
    199▕         while (\mb_strlen($ret) < $this->minHashLength) {
    200▕             $alphabet = $this->shuffle($alphabet, $alphabet);
    201▕             $ret = \mb_substr($alphabet, $halfLength) . $ret . \mb_substr($alphabet, 0, $halfLength);
    202▕
  ➜ 203▕             $excess = \mb_strlen($ret) - $this->minHashLength;`

minHashLength seems to be evaluating to a string. The actual ID on the record used was `(int)1`.

**Comment by mohkoma** [comment]
I got the same issue, the problem was I didn't publish the `vinkla/hashids` config file which requires connection configuration.
the solution was `php artisan vendor:publish`.
or create `config/hashids.php` file and past the code bellow.

```
<?php

return [

    'default' => 'main',

    /*
    |--------------------------------------------------------------------------
    | Hashids Connections
    |--------------------------------------------------------------------------
    |
    | Here are each of the connections setup for your application. Example
    | configuration has been included, but you may add as many connections as
    | you would like.
    |
    */

    'connections' => [

        'main' => [
            'salt' => env('APP_KEY'),
            'length' => 8,
            // 'alphabet' => 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890'
        ],

        'alternative' => [
            'salt' => env('APP_KEY'),
            'length' => 8,
            // 'alphabet' => 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890'
        ],

    ],

];
```

**Comment by SecondeJK** [comment]
OK I think as that's kind of trivial that I'm going to do a PR to add the publish command into the Readme

**Comment by SecondeJK** [comment]
#18
