### ISSUE TITLE
Wrong exception on invalid hash string

### ISSUE THREAD

**Issue by lidoma** [mtvs/eloquent-hashids#2]
Hi
When the hash string is invalid, an `InvalidArgumentException` throws via the `findByHashidOrFail()` method. I think, It supposed to have a not found exception.

**Comment by lidoma** [comment]
Also, via the `findByHashid()` method. It supposed to return a `NULL` value.

**Comment by mtvs** [comment]
Hi, sorry for the late response. Somehow I didn't receive the github notification emails.

It's fixed now with v1.2.0 release. 61f735a
