### ISSUE TITLE
Document customization of options

### ISSUE THREAD

**Issue by rverton** [mtvs/eloquent-hashids#7]
Hi,

I'm new to laravel and was not able to understand from your code how I can customize some options. For example I am looking to add a padding as described [here](https://github.com/vinkla/hashids#more-options) under 'Use padding to make your output ids longer'. Is it possible to do this with this extension?

Thanks,
robin

**Comment by mtvs** [comment]
Hi, 

As mentioned in the readme, this package internally uses vinkla/hashids, which has a config file that you can use to set the options of hashid connections. See its documentation for the instructions. 

Make sure to set the options on the connection that has been specified on the model, if no connection has been specified, the default connection is used.

Hope it helps.

**Comment by rverton** [comment]
Hi,
thanks a lot, I was able to figure it out this way. If someone is looking for the same thing:

First generate a config file for hashids:
`php artisan vendor:publish`

Then you can edit the `config/hashids.php` file and set a salt/length:
```
   'connections' => [

        'main' => [
            'salt' => 'qKboCxDDlP7l95JzrBg3',
            'length' => '9',
        ],

    ],
```
