### ISSUE TITLE
Laravel 7 support

### ISSUE THREAD

**Issue by ggolda** [mtvs/eloquent-hashids#9]
Please, add laravel 7 support. Currently when installing library, composer throws this error:
```
mtvs/eloquent-hashids v1.1.0 requires illuminate/database ~5.5.0|~5.6.0|~5.7.0|~5.8.0|^6.0
```
Looks like it should be easy to update since no major Eloquent changes in Laravel 7.

**Comment by mtvs** [comment]
v2.0.0 is now released to support L7.
